# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: quorum_set.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from . import external


@dataclass
class Node(betterproto.Message):
    responder_id: str = betterproto.string_field(1)
    public_key: external.Ed25519Public = betterproto.message_field(2)


@dataclass
class QuorumSetMember(betterproto.Message):
    node: "Node" = betterproto.message_field(1, group="member")
    inner_set: "QuorumSet" = betterproto.message_field(2, group="member")


@dataclass
class QuorumSet(betterproto.Message):
    threshold: int = betterproto.uint32_field(1)
    members: List["QuorumSetMember"] = betterproto.message_field(2)
